enum TFTPTest_FaultMode
{
   TFTP_TEST_FAULT_MODE_NORMAL_OPERATION,
   TFTP_TEST_FAULT_MODE_SRV_TIMEOUT,
   TFTP_TEST_FAULT_MODE_PKT_DUP,
   TFTP_TEST_FAULT_MODE_PKT_DROP,
   TFTP_TEST_FAULT_MODE_PKT_OUT_OF_ORDER,
   TFTP_TEST_FAULT_MODE_PKT_INVALID_TYPE,
   TFTP_TEST_FAULT_MODE_PKT_ERR,
   TFTP_TEST_FAULT_MODE_PKT_INVALID_ERR_CODE,
   TFTP_TEST_FAULT_MODE_SORCERERS_APPRENTICE,
};
